version: '3.8'

services:
  manager:
    build:
      context: ./Manager
      dockerfile: Dockerfile
    container_name: crackhash-manager
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    networks:
      - crackhash-network

  worker:
    build:
      context: ./Worker
      dockerfile: Dockerfile
    env_file:
      - ./.env
    networks:
      - crackhash-network
    depends_on:
      manager:
        condition: service_started
    # docker-compose up --scale worker=5

networks:
  crackhash-network:
    driver: bridge