spring.application.name=Worker

manager.port=${MANAGER_PORT:8080}

endpoint.worker.internal=${WORKER_INTERNAL_ENDPOINT:/internal/api/worker/crack/hash}
endpoint.worker.result=${WORKER_RESULT_ENDPOINT:/api/workers/result}
endpoint.worker.heartbeat=${WORKER_HEARTBEAT_ENDPOINT:/api/workers/health}
endpoint.worker.registration=${WORKER_REGISTRATION_ENDPOINT:/api/workers/register}

interval.heartbeat.send=${HEARTBEAT_SEND_INTERVAL:15000}

# SpringDoc OpenAPI paths
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Packages to scan for annotations
springdoc.packages-to-scan=com.example.worker.controllers

# Paths to include in documentation
springdoc.paths-to-match=/internal/api/**
spring.data.mongodb.uri=mongodb://mongo-primary:27017,mongo-replica-1:27017,mongo-replica-2:27017/taskmanager?replicaSet=rs0