spring.application.name=Manager

worker.registration.endpoint=${WORKER_REGISTRATION_ENDPOINT:/api/workers/register}
worker.heartbeat.endpoint=${WORKER_HEARTBEAT_ENDPOINT:/api/workers/health}

heartbeat.check.interval=${HEARTBEAT_CHECK_INTERVAL:30000}
spring.task.scheduling.pool.size=5
spring.task.scheduling.thread-name-prefix=heartbeat-scheduler-