spring.application.name=Manager

hash.alphabet=${HASH_ALPHABET:0123456789abcdefjhijklmnopqrstuvwxyz}

endpoint.user.status=${USER_STATUS_ENDPOINT:/api/hash/status}
endpoint.user.request=${USER_REQUEST_ENDPOINT:/api/hash/crack}
endpoint.worker.registration=${WORKER_REGISTRATION_ENDPOINT:/api/workers/register}
endpoint.worker.heartbeat=${WORKER_HEARTBEAT_ENDPOINT:/api/workers/health}

heartbeat.check.interval=${HEARTBEAT_CHECK_INTERVAL:30000}
spring.task.scheduling.pool.size=5
spring.task.scheduling.thread-name-prefix=heartbeat-scheduler-